// ══════════════════════════════════════════════════════════
//  포트폴리오 데이터 설정 파일
//  이 파일만 수정하면 홈페이지 포트폴리오가 자동으로 업데이트됩니다.
//
//  이미지 추가 방법 (2가지)
//  ① 자동:  터미널에서  node tools/add-portfolio.js  실행
//  ② 수동:  아래 배열에 항목 직접 추가 후 이미지를 assets/portfolio/ 에 저장
//
//  label 선택지: BRANDING / WEB / DETAIL PAGE / MARKETING / PRINT / OTHER
// ══════════════════════════════════════════════════════════

const PORTFOLIO_DATA = [
  {
    label: 'PRINT',
    title: '154체어 리플렛',
    description: '3단 리플렛 디자인',
    tags: ['3단 리플렛', '리플렛', '디자인'],
    image: 'assets/portfolio/154체어-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: 'KHSE 카탈로그',
    description: 'KHSE 카탈로그 디자인',
    tags: ['카탈로그', 'KHSE', '브로슈어'],
    image: 'assets/portfolio/KHSE-카탈로그.jpg',
  },
  {
    label: 'PRINT',
    title: 'SMANSA 수첩',
    description: '소만사(SMANSA) 수첩 디자인',
    tags: ['수첩', '포켓', '인쇄물'],
    image: 'assets/portfolio/SMANSA-수첩.jpg',
  },
  {
    label: 'PRINT',
    title: 'VIVAR 브로슈어',
    description: 'VIVAR 브로슈어 디자인',
    tags: ['카탈로그', '브로슈어', '가구업체'],
    image: 'assets/portfolio/VIVAR-브로슈어.jpg',
  },
  {
    label: 'PRINT',
    title: '한국석유공사 ESG보고서',
    description: '한국석유공사 ESG보고서 디자인',
    tags: ['ESG보고서', 'ESG', '지속가능경영', '보고서', '한국석유공사'],
    image: 'assets/portfolio/가스안전공사-ESG보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '가스안전공사 연차보고서',
    description: '가스안전공사 연차보고서',
    tags: ['ESG보고서', 'ESG', '지속가능경영', '보고서', '가스안전공사'],
    image: 'assets/portfolio/가스안전공사-연차보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '경북테크노파크 ESG보고서',
    description: '경북테크노파크 ESG보고서',
    tags: ['ESG보고서', 'ESG', '지속가능경영', '보고서', '경북테크노파크'],
    image: 'assets/portfolio/경북테크노파크-ESG보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '국립광주과학관 지속가능경영 ESG보고서',
    description: '국립광주과학관 ESG보고서',
    tags: ['ESG보고서', 'ESG', '지속가능경영', '보고서', '국립광주과학관'],
    image: 'assets/portfolio/국립광주과학관-지속가능경영-ESG보고서.jpg',
  },
  {
    label: 'WEB',
    title: '근로복지공단 PPT',
    description: '근로복지공단 연차 보고서 PPT 디자인',
    tags: ['연차보고서', '공공기관', 'PPT', '보고서', '근로복지공단'],
    image: 'assets/portfolio/근로복지공단-PPT.jpg',
  },
  {
    label: 'PRINT',
    title: '기술보증기금 ESG 보고서',
    description: '기술보증기금 ESG 보고서 디자인',
    tags: ['ESG보고서', 'ESG', '지속가능경영', '보고서', '기술보증기금'],
    image: 'assets/portfolio/기술보증기금-ESG-보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '나는 죽을때까지 기자다 자서전',
    description: '나는 죽을때까지 기자다 자서전 디자인',
    tags: ['자서전', '책자', '개인', '책발간'],
    image: 'assets/portfolio/나는-죽을때까지-기자다-자서전.jpg',
  },
  {
    label: 'PRINT',
    title: '대림건기 명함',
    description: '대림건기 조용석 대표님 명함 디자인',
    tags: ['명함', '인쇄', '대표', '직급', '건설', '중기', '명함', '디자인'],
    image: 'assets/portfolio/대림건기-명함.jpg',
  },
  {
    label: 'PRINT',
    title: '대한적십자 해외연수보고서',
    description: '대한적십자 해외연수 보고서 디자인',
    tags: ['연수', '해외', '보고서', '디자인', '책자', '대한적십자', '소식지'],
    image: 'assets/portfolio/대한적십자-해외연수보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '동창섬유 카탈로그 패키지',
    description: '동창섬유 카탈로그 패키지 디자인',
    tags: ['패키지', '책자', '카탈로그', '동창섬유', '회사소개', '디자인'],
    image: 'assets/portfolio/동창섬유-카탈로그-패키지.jpg',
  },
  {
    label: 'PRINT',
    title: '동행 소식지',
    description: '동행 소식지 디자인',
    tags: ['소식지', '인쇄', '디자인', '책자', '정기 간행물'],
    image: 'assets/portfolio/동행-소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '두잉굿센터 연차보고서',
    description: '두잉굿센터 연차보고서 디자인',
    tags: ['연차보고서', '보고서', '디자인', '두잉굿센터'],
    image: 'assets/portfolio/두잇굿센터-연차보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '메가오투 패키지',
    description: '메가오투 패키지 디자인',
    tags: ['패키지', '메가오투', '디자인', '박스', '3D'],
    image: 'assets/portfolio/메가오투-패키지.jpg',
  },
  {
    label: 'PRINT',
    title: '모두모아 소식지',
    description: '모두모아 간행물 소식지 디자인',
    tags: ['공공기관', '소식지', '디자인', '모두모아', '강동구'],
    image: 'assets/portfolio/모두모아-소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '범어 라클라쎄 리플렛',
    description: '분양 광고 범어 라클라쎄 리플렛 디자인',
    tags: ['리플렛', '라클라쎄', '리플렛 디자인', '분양대행', '디자인', '광고기획', '기획사'],
    image: 'assets/portfolio/범어-라클라쎄-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: '범어 라클라쎄 브로슈어',
    description: '분양 광고 범어 라클라쎄 브로슈어 디자인',
    tags: ['분양', '광고', '분양대행', '라클라쎄', '리플렛', '디자인', '광고기획', '기획사'],
    image: 'assets/portfolio/범어-라클라쎄-브로슈어.jpg',
  },
  {
    label: 'PRINT',
    title: '블랑키아 카탈로그',
    description: '블랑키아 제품 카탈로그 디자인',
    tags: ['블랑키아', '제품', '카탈로그', '디자인', '책자', '광고'],
    image: 'assets/portfolio/블랑키아-카탈로그.jpg',
  },
  {
    label: 'PRINT',
    title: '서울정 정신건강의학과의원 카탈로그',
    description: '서울정 정신건강의학과의원 카탈로그 디자인',
    tags: ['의료', '책자', '정신과', '책자제작', '카탈로그', '회사소개', '디자인'],
    image: 'assets/portfolio/서울정-정신건강의학과의원-카탈로그.jpg',
  },
  {
    label: 'PRINT',
    title: '성균관대학교 연차보고서',
    description: '성균관대학교 연차보고서 디자인',
    tags: ['연차보고서', '디자인', '보고서', '성균관대학교', '성대', '책자제작'],
    image: 'assets/portfolio/성균관대학교-연차보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '세운냉동 회사소개 PPT',
    description: '세운냉동 회사소개 PPT 디자인',
    tags: ['PPT', '디자인', '회사소개', '제품소개', '제품PPT'],
    image: 'assets/portfolio/세운냉동-회사소개-PPT.jpg',
  },
  {
    label: 'PRINT',
    title: '솔로몬텍 브로슈어',
    description: '솔로몬텍 브로슈어 디자인',
    tags: ['솔로몬텍', '브로슈어', '디자인', '책자', '회사소개'],
    image: 'assets/portfolio/솔로몬텍-브로슈어.jpg',
  },
  {
    label: 'PRINT',
    title: '시화가람 소식지',
    description: '시화가람 소식지 디자인',
    tags: ['시화가람', '간행물', '소식지', '디자인', '인쇄'],
    image: 'assets/portfolio/시화가람-소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '안산문화재단 연차보고서',
    description: '안산시 문화재단 연차보고서 디자인',
    tags: ['안산시', '문화재단', '연차보고서', '디자인', '연차', '보고서', '문화'],
    image: 'assets/portfolio/안산문화재단-연차보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '안산시청소년지원센터 꿈드림 소식지',
    description: '안산시 청소년지원센터 꿈드림 소식지 디자인',
    tags: ['소식지', '안산시', '청소년지원센터', '청소년', '꿈드림', '디자인'],
    image: 'assets/portfolio/안산시청소년지원센터-꿈드림-소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '연세대학교 ESG 보고서',
    description: '연세대학교 미래캠퍼스 ESG 보고서',
    tags: ['ESG', '연세대학교', '미래캠퍼스', '대학교', 'ESG보고서', '디자인'],
    image: 'assets/portfolio/연세대학교-ESG-보고서.jpg',
  },
  {
    label: 'PRINT',
    title: '연세대학교 연차보고서',
    description: '연세대학교 ESG 보고서 디자인',
    tags: ['연세대학교', 'ESG', '보고서', '디자인', '지속가능경영', '대학교'],
    image: 'assets/portfolio/연세대학교-연차보고서.png',
  },
  {
    label: 'PRINT',
    title: '유타대학 룩북',
    description: '유타대학 룩북 디자인',
    tags: ['유타대학', '룩북', '대학교', '디자인'],
    image: 'assets/portfolio/유타대학-룩북.jpg',
  },
  {
    label: 'PRINT',
    title: '이런협력 저런연대 보고서',
    description: '이런협력저런연대 보고서',
    tags: ['이런협력저런연대', '보고서', '단행물', '디자인'],
    image: 'assets/portfolio/이런협력-저런연대-보고서.jpg',
  },
  {
    label: 'BRANDING',
    title: '이상형 초대 개인전 포스터',
    description: '이상형 초대 개인전 포스터 디자인',
    tags: ['이상형', '초대', '개인전', '포스터', '책자', '디자인', '도룩'],
    image: 'assets/portfolio/이상형-초대-개인전-포스터.jpg',
  },
  {
    label: 'PRINT',
    title: '중구의류제조업체 라이브러리',
    description: '중구청 중구의류제조업체 라이브러리 디자인',
    tags: ['라이브러리', '중구청', '중구의류', '제조업체', '중구의류제조업체', '책자', '디자인'],
    image: 'assets/portfolio/중구의류제조업체-라이브러리.jpg',
  },
  {
    label: 'PRINT',
    title: '지앤지주간보호센터 소식지',
    description: '지앤지주간보호센터 소식지 디자인',
    tags: ['시냇가에 심은나무', '소식지', '장애시설', '책자제작', '지앤지주간보호센터', '디자인'],
    image: 'assets/portfolio/지앤지주간보호센터-소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '충남대학교 2025 소식지',
    description: '충남대학교 2025 소식지',
    tags: ['충남대', '충남대학교', '대학교', '소식지', '디자인', '간행물', '책자제작'],
    image: 'assets/portfolio/충남대학교-2025소식지.jpg',
  },
  {
    label: 'PRINT',
    title: '킨더가르텐 리플렛',
    description: '킨더가르텐 어린이집 리플렛 디자인',
    tags: ['리플렛', '디자인', '킨더가르텐', '어린이지', '유치원', '3단 리플렛'],
    image: 'assets/portfolio/킨더가르텐-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: '팬덤박스 리플렛',
    description: '팬덤박스 리플렛 디자인',
    tags: ['팬덤박스', '리플렛', '디자인', '2단 리플렛'],
    image: 'assets/portfolio/팬덤박스-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: '퍼스텝 카탈로그',
    description: '퍼스텝 카탈로그 디자인',
    tags: ['퍼스텝', '패키지', '업체', '회사소개', '회사소개서', '디자인', '소개서', '브로슈어'],
    image: 'assets/portfolio/퍼스텝-카탈로그.jpg',
  },
  {
    label: 'PRINT',
    title: '하이쓰리디 리플렛',
    description: '하이쓰리디 리플렛 디자인',
    tags: ['리플렛', '디자인', '하이쓰리디', '3단 리플렛', '대학교'],
    image: 'assets/portfolio/하이쓰리디-FLVMFFPT.jpg',
  },
  {
    label: 'PRINT',
    title: '한국도로교통공단 지속가능경영보고서',
    description: '한국도로교통공단 지속가능경영보고서 디자인',
    tags: ['보고서', '한국도로교통공단', '지속가능경영보고서', 'ESG', 'ESG보고서', '디자인', '공공기관'],
    image: 'assets/portfolio/한국도로교통공단-지속가능경영보고서.png',
  },
  {
    label: 'PRINT',
    title: '한국로봇산업협력 매뉴얼북',
    description: '한국로봇산업협력 매뉴얼북 디자인',
    tags: ['매뉴얼북', '매뉴얼', '디자인', '한국', '로봇산업협력', '안전매뉴얼', '안전'],
    image: 'assets/portfolio/한국로봇산업협력-매뉴얼북.jpg',
  },
  {
    label: 'PRINT',
    title: '한국시과학연구소 제안서',
    description: '한국시과학연구소 제안서 디자인',
    tags: ['제안서', '디자인', '시과학', '한국시과학', '연구소'],
    image: 'assets/portfolio/한국시과학연구소-제안서.jpg',
  },
  {
    label: 'PRINT',
    title: '한국외국어대학교 리플렛',
    description: '한국외국어대학교 리플렛 디자인',
    tags: ['리플렛', '한국외국어대학교', '대학교', '리플렛', '디자인', '4단 리플렛'],
    image: 'assets/portfolio/한국외국어대학교-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: '한국전통음악 이서영 리플렛',
    description: '한국전통음악 이서영 리플렛',
    tags: ['이서영', '리플렛', '한국전통음악', '모집', '광고', '4단 리플렛'],
    image: 'assets/portfolio/한국전통국악-리플렛.jpg',
  },
  {
    label: 'PRINT',
    title: '헤이푸드 카탈로그',
    description: '헤이푸드 카탈로그 디자인',
    tags: ['헤이푸드', '카탈로그', '디자인', '책자', '음식점', '가공', '포장', '도시락'],
    image: 'assets/portfolio/헤이푸드-카탈로그.jpg',
  },
];
